name: Dev Preview (PR to dev)

on:
  pull_request:
    branches: ['dev']

concurrency:
  group: preview-${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  ci:
    name: Test • Build (Angular 20)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (CI clean)
        run: npm ci

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Unit tests (Karma Headless)
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          echo "CHROME_BIN is $CHROME_BIN"
          npx ng test --watch=false --browsers=ChromeHeadless --no-progress --source-map=false

      - name: Build (prod)
        run: npx ng build --configuration production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/**

  preview:
    name: Firebase Hosting Preview (expires in 3 days)
    needs: ci
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist

      - name: Deploy Preview (kalmy-dev)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
          target: dev
          channelId: pr-${{ github.event.pull_request.number }}
          expires: '3d'
          entryPoint: .
